{"fn":"main","ip":0,"op":"CONST","line":6,"stack":[]}
{"fn":"main","ip":2,"op":"CONST","line":6,"stack":[2]}
{"fn":"main","ip":4,"op":"CALL","line":6,"stack":[2,3]}
{"fn":"add","ip":0,"op":"GET_LOCAL","line":3,"stack":[2,3]}
{"fn":"add","ip":2,"op":"GET_LOCAL","line":3,"stack":[2,3,2]}
{"fn":"add","ip":4,"op":"ADD","line":3,"stack":[2,3,2,3]}
{"fn":"add","ip":6,"op":"RETURN","line":3,"stack":[2,3,5]}
{"fn":"main","ip":7,"op":"RETURN","line":6,"stack":[5]}
